apiVersion: v1
kind: Service
metadata:
    name: post-serv
spec:
    type: NodePort
    selector: # we are telling the service to try to find all the different pods with a label of app post and expose traffic or expose those pods to the outside world
        app: posts
    ports: #list out all the different ports that want to expose on the target pod
        - name: posts
          protocol: TCP
          port: 4000 # port for the Node Port Service
          targetPort: 4000 # the port that is attached to the container
